#!/bin/bash
set -euo pipefail

# Fedora Atomic ClamAV setup:
# - Layers packages (rpm-ostree) if missing
# - Configures: freshclam updates, clamd@scan, clamonacc on-access, and a periodic scan timer
# - Sets sane defaults and enables services
# - If layering was done without live-apply, schedules a post-install for next reboot
#
# See the LICENSE file at the top of the project tree for copyright
# and license details.

APPLY_LIVE=0
for arg in "${@:-}"; do
  case "$arg" in
    --apply-live) APPLY_LIVE=1 ;;
    -h|--help)
      cat <<'USAGE'
Usage:
  sudo ./setup-clamav.bash [--apply-live]

Notes:
  - On Fedora Atomic, rpm-ostree typically needs a reboot to apply layered packages.
  - If a reboot is needed, this script schedules an automatic post-install that runs
    after the reboot.
USAGE
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "Run as root (use sudo)." >&2
    exit 1
  fi
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

backup_once() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  local b="${f}.bak"
  [[ -e "$b" ]] && return 0
  cp -a "$f" "$b"
}

ensure_kv_line() {
  # Ensures a single "Key Value" line exists (replaces commented/old)
  local file="$1" key="$2" value="$3"
  if grep -Eq "^[[:space:]]*#?[[:space:]]*${key}\b" "$file"; then
    sed -ri "s|^[[:space:]]*#?[[:space:]]*${key}\b.*|${key} ${value}|g" "$file"
  else
    printf "\n%s %s\n" "$key" "$value" >>"$file"
  fi
}

ensure_multi_line() {
  # Ensures an exact "Key Value" line exists (can repeat key multiple times)
  local file="$1" key="$2" value="$3"
  if ! grep -Fxq "${key} ${value}" "$file"; then
    printf "%s %s\n" "$key" "$value" >>"$file"
  fi
}

comment_out_example() {
  local file="$1"
  # Many ClamAV sample configs contain "Example" which must be removed/commented for services to start.
  sed -ri 's|^[[:space:]]*Example[[:space:]]*$|# Example|g' "$file" || true
}

write_file_if_missing() {
  local path="$1"
  local content="$2"
  if [[ ! -f "$path" ]]; then
    install -d -m 0755 "$(dirname "$path")"
    printf "%s\n" "$content" >"$path"
  fi
}

configure_sysctl_inotify() {
  # ClamAV on-access uses inotify for directory determination; large trees can exhaust watches.
  # ClamAV docs recommend increasing max_user_watches (example 524288). :contentReference[oaicite:1]{index=1}
  local sysctl_file="/etc/sysctl.d/99-clamav-inotify.conf"
  cat >"$sysctl_file" <<'EOF'
# Increase inotify watches for ClamAV On-Access scanning (clamonacc)
fs.inotify.max_user_watches = 524288
EOF
  sysctl --system >/dev/null 2>&1 || true
}

configure_freshclam() {
  install -d -m 0755 /var/log/clamav
  local f="/etc/freshclam.conf"
  backup_once "$f"

  # Minimal safe config (Fedora package provides the service, but we ensure sane defaults).
  write_file_if_missing "$f" "#
# freshclam.conf - generated by clamav-atomic-setup
#"

  comment_out_example "$f"
  ensure_kv_line "$f" "DatabaseDirectory" "/var/lib/clamav"
  ensure_kv_line "$f" "UpdateLogFile" "/var/log/freshclam.log"
  ensure_kv_line "$f" "LogTime" "yes"
  ensure_kv_line "$f" "LogVerbose" "no"
  ensure_kv_line "$f" "DatabaseOwner" "clamscan"
  # Notify clamd to reload DB after updates
  ensure_kv_line "$f" "NotifyClamd" "/etc/clamd.d/scan.conf"
}

configure_clamd_scanconf() {
  install -d -m 0755 /etc/clamd.d

  local conf="/etc/clamd.d/scan.conf"
  if [[ ! -f "$conf" ]]; then
    # Fedora clamd package includes a sample in /usr/share/doc/clamd/clamd.conf :contentReference[oaicite:2]{index=2}
    if [[ -f /usr/share/doc/clamd/clamd.conf ]]; then
      cp -a /usr/share/doc/clamd/clamd.conf "$conf"
    else
      cat >"$conf" <<'EOF'
# scan.conf - generated by clamav-atomic-setup
EOF
    fi
  fi

  backup_once "$conf"
  comment_out_example "$conf"

  # Base settings
  ensure_kv_line "$conf" "LogSyslog" "yes"
  ensure_kv_line "$conf" "DatabaseDirectory" "/var/lib/clamav"
  ensure_kv_line "$conf" "LocalSocket" "/run/clamd.scan/clamd.sock"
  ensure_kv_line "$conf" "FixStaleSocket" "yes"
  ensure_kv_line "$conf" "User" "clamscan"

  # On-access settings (ClamAV On-Access guide) :contentReference[oaicite:3]{index=3}
  # Paths requested + common mount roots:
  local include_paths=(
    "/var/home"
    "/tmp"
    "/run/media"
    "/mnt"
    "/var/mnt"
  )
  for p in "${include_paths[@]}"; do
    ensure_multi_line "$conf" "OnAccessIncludePath" "$p"
  done

  # Avoid loops and reduce risk:
  ensure_kv_line "$conf" "OnAccessExcludeUname" "clamscan"
  ensure_kv_line "$conf" "OnAccessExcludeRootUID" "yes"

  # Block access to infected files (prevention). :contentReference[oaicite:4]{index=4}
  ensure_kv_line "$conf" "OnAccessPrevention" "yes"
}

setup_onaccess_service_override() {
  # Fedora ships service units for clamonacc in the clamav package. :contentReference[oaicite:5]{index=5}
  local unit=""
  if systemctl list-unit-files --no-legend --type=service 2>/dev/null | awk '{print $1}' | grep -qx "clamav-clamonacc.service"; then
    unit="clamav-clamonacc.service"
  elif systemctl list-unit-files --no-legend --type=service 2>/dev/null | awk '{print $1}' | grep -qx "clamonacc.service"; then
    unit="clamonacc.service"
  else
    unit=""
  fi

  if [[ -z "$unit" ]]; then
    echo "Warning: no systemd unit found for clamonacc; skipping on-access scanning."
    return 0
  fi

  local dropin_dir="/etc/systemd/system/${unit}.d"
  install -d -m 0755 "$dropin_dir"

  # Override ExecStart to enforce:
  # - foreground (systemd)
  # - fdpass (better for LocalSocket permissions)
  # - log + quarantine
  # Note: /var/spool/quarantine ships with the clamav package. :contentReference[oaicite:6]{index=6}
  cat >"${dropin_dir}/override.conf" <<'EOF'
[Service]
ExecStart=
ExecStart=/usr/bin/clamonacc --foreground --fdpass --log=/var/log/clamonacc.log --move=/var/spool/quarantine
Restart=on-failure
RestartSec=5
EOF
}

setup_periodic_scan() {
  install -d -m 0755 /usr/local/sbin
  install -d -m 0755 /var/log/clamav
  install -d -m 0700 /var/spool/quarantine

  cat >/usr/local/sbin/clamav-scan-targets.bash <<'EOF'
#!/bin/bash
set -euo pipefail

LOG_DIR="/var/log/clamav"
QUAR="/var/spool/quarantine"
mkdir -p "$LOG_DIR" "$QUAR"

ts="$(date --iso-8601=seconds | tr ':' '-')"
log="${LOG_DIR}/clamdscan-${ts}.log"

targets=( "/var/home" "/tmp" )

# Detect mounted storage (common disk fs types). Filter out system pseudo mounts.
fstypes=(ext4 xfs btrfs f2fs vfat exfat ntfs ntfs3 hfsplus apfs udf iso9660)
if command -v findmnt >/dev/null 2>&1; then
  while IFS= read -r line; do
    # line: TARGET FSTYPE
    t="${line%% *}"
    case "$t" in
      ""|"/"|/proc*|/sys*|/run*|/dev*|/boot*|/var/lib/containers* ) continue ;;
    esac
    targets+=( "$t" )
  done < <(findmnt -rn -o TARGET,FSTYPE -t "$(IFS=,; echo "${fstypes[*]}")" 2>/dev/null || true)
fi

# Unique targets
mapfile -t uniq_targets < <(printf "%s\n" "${targets[@]}" | awk 'NF' | sort -u)

# Use clamd (faster) and pass FDs so clamd user can scan user files.
exec /usr/bin/clamdscan --multiscan --fdpass --infected --log="$log" --move="$QUAR" "${uniq_targets[@]}"
EOF
  chmod 0755 /usr/local/sbin/clamav-scan-targets.bash

  cat >/etc/systemd/system/clamav-target-scan.service <<'EOF'
[Unit]
Description=ClamAV: periodic scan of /var/home, /tmp, and mounted volumes
Wants=clamd@scan.service
After=clamd@scan.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/clamav-scan-targets.bash
EOF

  cat >/etc/systemd/system/clamav-target-scan.timer <<'EOF'
[Unit]
Description=ClamAV: scheduler for periodic scans

[Timer]
OnCalendar=daily
RandomizedDelaySec=1h
Persistent=true

[Install]
WantedBy=timers.target
EOF
}

enable_services() {
  systemctl daemon-reload

  # Update signatures first (clamd needs DB). :contentReference[oaicite:7]{index=7}
  systemctl enable --now clamav-freshclam.service || true
  freshclam || true

  systemctl enable --now clamd@scan.service || true

  if systemctl list-unit-files --no-legend --type=service 2>/dev/null | awk '{print $1}' | grep -qx "clamav-clamonacc.service"; then
    systemctl enable --now clamav-clamonacc.service || true
  elif systemctl list-unit-files --no-legend --type=service 2>/dev/null | awk '{print $1}' | grep -qx "clamonacc.service"; then
    systemctl enable --now clamonacc.service || true
  fi

  systemctl enable --now clamav-target-scan.timer || true
}

configure_all() {
  configure_sysctl_inotify
  configure_freshclam
  configure_clamd_scanconf
  setup_onaccess_service_override
  setup_periodic_scan

  # Restore SELinux contexts if available
  if command -v restorecon >/dev/null 2>&1; then
    restorecon -Rv /etc/clamd.d /etc/freshclam.conf /var/log/clamav /var/spool/quarantine >/dev/null 2>&1 || true
  fi

  enable_services
}

schedule_postinstall() {
  # If packages were layered but not live-applied, run config automatically after reboot.
  install -d -m 0755 /var/lib/clamav-atomic
  cat >/var/lib/clamav-atomic/postinstall.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
# Runs the same configuration steps once the layered packages are available after reboot.
# (Generated by clamav-atomic-setup.sh)

have_cmd() { command -v "$1" >/dev/null 2>&1; }
require_root() { [[ "${EUID:-$(id -u)}" -eq 0 ]] || { echo "root required" >&2; exit 1; }; }

backup_once() { local f="$1"; [[ -f "$f" ]] || return 0; local b="${f}.bak"; [[ -e "$b" ]] && return 0; cp -a "$f" "$b"; }
ensure_kv_line() { local file="$1" key="$2" value="$3"; if grep -Eq "^[[:space:]]*#?[[:space:]]*${key}\b" "$file"; then sed -ri "s|^[[:space:]]*#?[[:space:]]*${key}\b.*|${key} ${value}|g" "$file"; else printf "\n%s %s\n" "$key" "$value" >>"$file"; fi; }
ensure_multi_line() { local file="$1" key="$2" value="$3"; grep -Fxq "${key} ${value}" "$file" || printf "%s %s\n" "$key" "$value" >>"$file"; }
comment_out_example() { local file="$1"; sed -ri 's|^[[:space:]]*Example[[:space:]]*$|# Example|g' "$file" || true; }
write_file_if_missing() { local path="$1" content="$2"; [[ -f "$path" ]] || { install -d -m 0755 "$(dirname "$path")"; printf "%s\n" "$content" >"$path"; }; }

configure_sysctl_inotify() {
  cat >/etc/sysctl.d/99-clamav-inotify.conf <<'EOT'
# Increase inotify watches for ClamAV On-Access scanning (clamonacc)
fs.inotify.max_user_watches = 524288
EOT
  sysctl --system >/dev/null 2>&1 || true
}

configure_freshclam() {
  install -d -m 0755 /var/log/clamav
  local f="/etc/freshclam.conf"
  backup_once "$f"
  write_file_if_missing "$f" "# freshclam.conf - generated by clamav-atomic-setup"
  comment_out_example "$f"
  ensure_kv_line "$f" "DatabaseDirectory" "/var/lib/clamav"
  ensure_kv_line "$f" "UpdateLogFile" "/var/log/freshclam.log"
  ensure_kv_line "$f" "LogTime" "yes"
  ensure_kv_line "$f" "LogVerbose" "no"
  ensure_kv_line "$f" "DatabaseOwner" "clamscan"
  ensure_kv_line "$f" "NotifyClamd" "/etc/clamd.d/scan.conf"
}

configure_clamd_scanconf() {
  install -d -m 0755 /etc/clamd.d
  local conf="/etc/clamd.d/scan.conf"
  if [[ ! -f "$conf" ]]; then
    if [[ -f /usr/share/doc/clamd/clamd.conf ]]; then
      cp -a /usr/share/doc/clamd/clamd.conf "$conf"
    else
      echo "# scan.conf - generated" >"$conf"
    fi
  fi
  backup_once "$conf"
  comment_out_example "$conf"
  ensure_kv_line "$conf" "LogSyslog" "yes"
  ensure_kv_line "$conf" "DatabaseDirectory" "/var/lib/clamav"
  ensure_kv_line "$conf" "LocalSocket" "/run/clamd.scan/clamd.sock"
  ensure_kv_line "$conf" "FixStaleSocket" "yes"
  ensure_kv_line "$conf" "User" "clamscan"

  for p in /var/home /tmp /run/media /mnt /var/mnt; do
    ensure_multi_line "$conf" "OnAccessIncludePath" "$p"
  done
  ensure_kv_line "$conf" "OnAccessExcludeUname" "clamscan"
  ensure_kv_line "$conf" "OnAccessExcludeRootUID" "yes"
  ensure_kv_line "$conf" "OnAccessPrevention" "yes"
}

setup_onaccess_service_override() {
  local unit=""
  if systemctl list-unit-files --no-legend --type=service 2>/dev/null | awk '{print $1}' | grep -qx "clamav-clamonacc.service"; then
    unit="clamav-clamonacc.service"
  elif systemctl list-unit-files --no-legend --type=service 2>/dev/null | awk '{print $1}' | grep -qx "clamonacc.service"; then
    unit="clamonacc.service"
  else
    return 0
  fi

  local dropin_dir="/etc/systemd/system/${unit}.d"
  install -d -m 0755 "$dropin_dir"
  cat >"${dropin_dir}/override.conf" <<'EOT'
[Service]
ExecStart=
ExecStart=/usr/bin/clamonacc --foreground --fdpass --log=/var/log/clamonacc.log --move=/var/spool/quarantine
Restart=on-failure
RestartSec=5
EOT
}

setup_periodic_scan() {
  install -d -m 0755 /usr/local/sbin
  install -d -m 0755 /var/log/clamav
  install -d -m 0700 /var/spool/quarantine

  cat >/usr/local/sbin/clamav-scan-targets.bash <<'EOT'
#!/usr/bin/env bash
set -euo pipefail
LOG_DIR="/var/log/clamav"
QUAR="/var/spool/quarantine"
mkdir -p "$LOG_DIR" "$QUAR"
ts="$(date --iso-8601=seconds | tr ':' '-')"
log="${LOG_DIR}/clamdscan-${ts}.log"
targets=( "/var/home" "/tmp" )
fstypes=(ext4 xfs btrfs f2fs vfat exfat ntfs ntfs3 hfsplus apfs udf iso9660)
if command -v findmnt >/dev/null 2>&1; then
  while IFS= read -r line; do
    t="${line%% *}"
    case "$t" in ""|"/"|/proc*|/sys*|/run*|/dev*|/boot*|/var/lib/containers* ) continue ;; esac
    targets+=( "$t" )
  done < <(findmnt -rn -o TARGET,FSTYPE -t "$(IFS=,; echo "${fstypes[*]}")" 2>/dev/null || true)
fi
mapfile -t uniq_targets < <(printf "%s\n" "${targets[@]}" | awk 'NF' | sort -u)
exec /usr/bin/clamdscan --multiscan --fdpass --infected --log="$log" --move="$QUAR" "${uniq_targets[@]}"
EOT
  chmod 0755 /usr/local/sbin/clamav-scan-targets.bash

  cat >/etc/systemd/system/clamav-target-scan.service <<'EOT'
[Unit]
Description=ClamAV: escaneo periódico de /var/home, /tmp y unidades montadas
Wants=clamd@scan.service
After=clamd@scan.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/clamav-scan-targets.bash
EOT

  cat >/etc/systemd/system/clamav-target-scan.timer <<'EOT'
[Unit]
Description=ClamAV: programador de escaneos periódicos

[Timer]
OnCalendar=daily
RandomizedDelaySec=1h
Persistent=true

[Install]
WantedBy=timers.target
EOT
}

enable_services() {
  systemctl daemon-reload
  systemctl enable --now clamav-freshclam.service || true
  freshclam || true
  systemctl enable --now clamd@scan.service || true
  if systemctl list-unit-files --no-legend --type=service 2>/dev/null | awk '{print $1}' | grep -qx "clamav-clamonacc.service"; then
    systemctl enable --now clamav-clamonacc.service || true
  elif systemctl list-unit-files --no-legend --type=service 2>/dev/null | awk '{print $1}' | grep -qx "clamonacc.service"; then
    systemctl enable --now clamonacc.service || true
  fi
  systemctl enable --now clamav-target-scan.timer || true
}

main() {
  require_root
  configure_sysctl_inotify
  configure_freshclam
  configure_clamd_scanconf
  setup_onaccess_service_override
  setup_periodic_scan
  if command -v restorecon >/dev/null 2>&1; then
    restorecon -Rv /etc/clamd.d /etc/freshclam.conf /var/log/clamav /var/spool/quarantine >/dev/null 2>&1 || true
  fi
  enable_services

  # Disable and remove this postinstall unit after success
  systemctl disable --now clamav-atomic-postinstall.service >/dev/null 2>&1 || true
  rm -f /etc/systemd/system/clamav-atomic-postinstall.service
  systemctl daemon-reload >/dev/null 2>&1 || true
  rm -f /var/lib/clamav-atomic/postinstall.sh
}
main
EOF
  chmod 0755 /var/lib/clamav-atomic/postinstall.sh

  cat >/etc/systemd/system/clamav-atomic-postinstall.service <<'EOF'
[Unit]
Description=ClamAV Atomic: post-install (configuration after reboot)
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/bash /var/lib/clamav-atomic/postinstall.sh

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable clamav-atomic-postinstall.service >/dev/null 2>&1 || true
}

install_if_needed_atomic() {
  if ! have_cmd rpm-ostree; then
    echo "rpm-ostree not found. This script is intended for Fedora Atomic (rpm-ostree)." >&2
    exit 1
  fi

  local missing=()
  for p in clamav clamd clamav-freshclam; do
    rpm -q "$p" >/dev/null 2>&1 || missing+=( "$p" )
  done

  if ((${#missing[@]})); then
    echo "Layering missing packages: ${missing[*]}"
    local cmd=( rpm-ostree install --assumeyes )
    if [[ "$APPLY_LIVE" -eq 1 ]] && rpm-ostree install --help 2>/dev/null | grep -q -- '--apply-live'; then
      cmd+=( --apply-live )
      echo "Using --apply-live (if supported)."
    fi
    "${cmd[@]}" "${missing[@]}"
  fi
}

main() {
  require_root

  install_if_needed_atomic

  # If packages were just layered and not live-applied, clamscan/clamonacc may not exist yet.
  if ! have_cmd clamscan || ! have_cmd clamdscan || ! have_cmd clamonacc; then
    echo "Packages appear pending application (common on Atomic)."
    echo "Scheduling automatic configuration for the next boot."
    schedule_postinstall
    echo "Reboot to complete installation and configuration."
    exit 0
  fi

  configure_all

  echo "Done. Services/timer configured:"
  echo "  - clamav-freshclam (signature updates)"
  echo "  - clamd@scan (daemon)"
  echo "  - clamonacc (on-access, if the unit exists)"
  echo "  - clamav-target-scan.timer (daily scan with quarantine)"
  echo ""
  echo "Logs:"
  echo "  - /var/log/freshclam.log"
  echo "  - /var/log/clamonacc.log"
  echo "  - /var/log/clamav/clamdscan-*.log"
  echo "Quarantine:"
  echo "  - /var/spool/quarantine"
}

main
